<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <WarningsNotAsErrors>0612,0618</WarningsNotAsErrors>
    <PackageId>Avalonia.AvaloniaEdit</PackageId>
    <PackageDescription>This project is a port of AvalonEdit, a WPF-based text editor for Avalonia.</PackageDescription>
    <PackageTags>editor;code-editor;avalonia;text-editor;netstandard</PackageTags>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('$(AvaloniaSourceDir)')">
    <IncludeAvaloniaGenerators>true</IncludeAvaloniaGenerators>
  </PropertyGroup>
  <ItemGroup Condition="Exists('$(AvaloniaSourceDir)')">
    <ProjectReference Include="$(AvaloniaSourceDir)packages\Avalonia\Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('$(AvaloniaSourceDir)')">
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.xshd;**\*.resx;" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
    <AvaloniaResource Include="**\*.xaml;Assets\*;" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SR.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="SR.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SR.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Import Project="$(AvaloniaSourceDir)build\BuildTargets.targets" Condition="Exists('$(AvaloniaSourceDir)')" />
  <Import Project="$(AvaloniaSourceDir)build\SourceGenerators.props" Condition="Exists('$(AvaloniaSourceDir)')" />
</Project>
