<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageDescription>TextMate integration for AvaloniaEdit.</PackageDescription>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(AvaloniaSourceDir)')">
    <ProjectReference Include="$(AvaloniaSourceDir)packages\Avalonia\Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('$(AvaloniaSourceDir)')">
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaloniaEdit\AvaloniaEdit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
  </ItemGroup>
</Project>
